import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import NavBar from '../../components/NavBar'
import { Main } from '../../components/Main'

import Projects from '../../components/Projects'
import Contact from '../../components/Contact'
import SkillsList from '../../components/SkillsList'
import AboutMe from '../../components/AboutMe'



export default function Home() {
  return (
    <>
      <Head>
        <title>Tor Software Engineer </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main />
      <AboutMe />
      <SkillsList />
      <Projects />
      <Contact />
    </>
  )
}
